services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=ubd'
      - 'MYSQL_PASSWORD='
      - 'MYSQL_ROOT_PASSWORD='
      - 'MYSQL_USER=root'
    ports:
      - '3306'
